var certificates = [
    { name: " تقى راسم فرهود", pdf: "certificates/تقى راسم.pdf" },
    { name: " ابرار ضياء طالب", pdf: "certificates/ابرار.pdf" },
    { name: " مريم مهدي رشيد", pdf: "certificates/مريم مهدي.pdf" },
    { name: " هبه نشأت عبد الزهرة", pdf: "certificates/هبه نشأت.pdf" },
    { name: " احمد علي عبد الوهاب", pdf: "certificates/احمد علي.pdf" },
    { name: " نبأ عبد الباسط", pdf: "certificates/نبأ.pdf" },
    { name: " يسر زياد طارق", pdf: "certificates/يسر.pdf" },
    { name: " علي صفاء الدين حسن", pdf: "certificates/علي ص.pdf" },
    { name: " عبدالله محمود جلوب", pdf: "certificates/عبدالله محمود.pdf" },
    { name: " زينب احمد حسين", pdf: "certificates/زينب احمد حسين.pdf" },
    { name: " الاء لطيف احمد", pdf: "certificates/الاء لطيف.pdf" },
    { name: " مُقدس سجاد رزاق", pdf: "certificates/مُقدس سجاد رزاق.pdf" },
    { name: " امير صباح هشام", pdf: "certificates/امير صباح.pdf" },
    { name: " بنين علي ردام", pdf: "certificates/بنين.pdf" },
    { name: " يوسف وسام جبار", pdf: "certificates/يوسف.pdf" },
    { name: " محمد علي عباس", pdf: "certificates/محمد علي.pdf" },
    { name: "طارق عبدالكريم", pdf: "certificates/tariq_abdulkarim.pdf" },
    { name: "ايلاف صباح كريم", pdf: "certificates/Elaf Sabah Karim.pdf" },
    { name: "مهيمن حيدر طالب", pdf: "certificates/Muhemn Haidar Talib.pdf" },
    { name: "مريم عبدالمجيد", pdf: "certificates/mariam_abdelmageed.pdf" },
    { name: "فاضل هاشم فاضل", pdf: "certificates/Fadhil Hashim Fadhil.pdf" },
    { name: "حسن محمد خليل", pdf: "certificates/Hasan mohammed khalil.pdf" },
    { name: "أيمن خاطر عوض", pdf: "certificates/Ayman Khatar Awadh.pdf" },
    { name: "حسام الدين", pdf: "certificates/hesham_eldin.pdf" },
    { name: " همام احمد حسين", pdf: "certificates/همام احمد.pdf" },
    { name: " احمد عبدالمطلب رضا", pdf: "certificates/احمد عبد.pdf" },
    { name: "نهى عبدالعزيز", pdf: "certificates/noha_abdulaziz.pdf" },
    { name: "وائل أحمد", pdf: "certificates/wael_ahmed.pdf" },
    { name: "طارق زياد طارق", pdf: "certificates/Tariq Zeyad Tariq.pdf" },
    { name: "براء محمد مصعب", pdf: "certificates/Baraa Mohammed Musab.pdf" },
    { name: "ملاك هشام يوسف", pdf: "certificates/ملاك.pdf" },
    { name: "بلال عمر", pdf: "certificates/bilal_omar.pdf" },
    { name: "فرح محمد", pdf: "certificates/farah_mohamed.pdf" },
    { name: "جمال عاصف عبدالرزاق", pdf: "certificates/جمال.pdf" },
    { name: "فرقان محسن خليف", pdf: "certificates/فرقان.pdf" },
    { name: "زينب حسن", pdf: "certificates/zeinab_hassan.pdf" },
    { name: "عبدالرحمن سامي", pdf: "certificates/abdurrahman_sami.pdf" },
    { name: "حسين علوان خليل", pdf: "certificates/Hussein Alwan Khalil.pdf" },
    { name: "قمر سرمد محمد علي", pdf: "certificates/Qamar Sarmed Mohammed Ali.pdf" },
    { name: "نبأ عامر ناصر", pdf: "certificates/Nabaa Amer Nasser.pdf" },
    { name: "علي حسن فلاح", pdf: "certificates/ALI HASSAN FALAH.pdf" },
    { name: "زين عبدالحميد", pdf: "certificates/zein_abdulhamid.pdf" },
    { name: "منن مهند نصر", pdf: "certificates/Minan Muhanned Nasser.pdf" },
    { name: "خليل إبراهيم", pdf: "certificates/khaleel_ibrahim.pdf" },
    { name: "مرام محمد علي", pdf: "certificates/Maram Mohmeed Ali.pdf" },
    { name: "عباس فاضل", pdf: "certificates/Abbas Fadhil.pdf" },
    { name: "رزان محمد", pdf: "certificates/razan_mohamed.pdf" }
];


