var certificates = [
    { name: " تقى راسم فرهود", pdf: "certificates/تقى راسم.pdf" },
    { name: " ابرار ضياء طالب", pdf: "certificates/ابرار.pdf" },
    { name: " مريم مهدي رشيد", pdf: "certificates/مريم مهدي.pdf" },
    { name: " هبه نشأت عبد الزهرة", pdf: "certificates/هبه نشأت.pdf" },
    { name: " احمد علي عبد الوهاب", pdf: "certificates/احمد علي.pdf" },
    { name: " نبأ عبد الباسط", pdf: "certificates/نبأ.pdf" },
    { name: " يسر زياد طارق", pdf: "certificates/يسر.pdf" },
    { name: " علي صفاء الدين حسن", pdf: "certificates/علي ص.pdf" },
    { name: " عبدالله محمود جلوب", pdf: "certificates/عبدالله محمود.pdf" },
    { name: " زينب احمد حسين", pdf: "certificates/زينب احمد حسين.pdf" },
    { name: " الاء لطيف احمد", pdf: "certificates/الاء لطيف.pdf" },
    { name: " مُقدس سجاد رزاق", pdf: "certificates/مُقدس سجاد رزاق.pdf" },
    { name: " امير صباح هشام", pdf: "certificates/امير صباح.pdf" },
    { name: " بنين علي ردام", pdf: "certificates/بنين.pdf" },
    { name: " يوسف وسام جبار", pdf: "certificates/يوسف.pdf" },
    { name: " محمد علي عباس", pdf: "certificates/محمد علي.pdf" },
    { name: "طارق عبدالكريم", pdf: "certificates/tariq_abdulkarim.pdf" },
    { name: "ليلى حسن", pdf: "certificates/leila_hassan.pdf" },
    { name: "جمال فريد", pdf: "certificates/jamal_fareed.pdf" },
    { name: "مريم عبدالمجيد", pdf: "certificates/mariam_abdelmageed.pdf" },
    { name: "أشرف محمود", pdf: "certificates/ashraf_mahmoud.pdf" },
    { name: "إيمان كمال", pdf: "certificates/eman_kamal.pdf" },
    { name: "زياد ناصر", pdf: "certificates/ziad_nasser.pdf" },
    { name: "حسام الدين", pdf: "certificates/hesham_eldin.pdf" },
    { name: " همام احمد حسين", pdf: "certificates/همام احمد.pdf" },
    { name: " احمد عبدالمطلب رضا", pdf: "certificates/احمد عبد.pdf" },
    { name: "نهى عبدالعزيز", pdf: "certificates/noha_abdulaziz.pdf" },
    { name: "وائل أحمد", pdf: "certificates/wael_ahmed.pdf" },
    { name: "دينا مجدي", pdf: "certificates/dina_magdy.pdf" },
    { name: "ماهر حسن", pdf: "certificates/maher_hassan.pdf" },
    { name: "ملاك هشام يوسف", pdf: "certificates/ملاك.pdf" },
    { name: "بلال عمر", pdf: "certificates/bilal_omar.pdf" },
    { name: "فرح محمد", pdf: "certificates/farah_mohamed.pdf" },
    { name: "جواد سليم", pdf: "certificates/jawad_salim.pdf" },
    { name: "فرقان محسن خليف", pdf: "certificates/فرقان.pdf" },
    { name: "زينب حسن", pdf: "certificates/zeinab_hassan.pdf" },
    { name: "عبدالرحمن سامي", pdf: "certificates/abdurrahman_sami.pdf" },
    { name: "لمياء طارق", pdf: "certificates/lamia_tariq.pdf" },
    { name: "علاء نبيل", pdf: "certificates/alaa_nabeel.pdf" },
    { name: "صفية كمال", pdf: "certificates/safia_kamal.pdf" },
    { name: "هيثم فؤاد", pdf: "certificates/haitham_fouad.pdf" },
    { name: "زين عبدالحميد", pdf: "certificates/zein_abdulhamid.pdf" },
    { name: "حياة مصطفى", pdf: "certificates/hayat_mostafa.pdf" },
    { name: "خليل إبراهيم", pdf: "certificates/khaleel_ibrahim.pdf" },
    { name: "نادين يوسف", pdf: "certificates/nadeen_yousef.pdf" },
    { name: "رمزي ناصر", pdf: "certificates/ramzi_nasser.pdf" },
    { name: "رزان محمد", pdf: "certificates/razan_mohamed.pdf" }
];
